language: python
python:
  - 3.7
  - 3.5
  - 2.7

jobs:
  include:
    - if: branch IN (master, develop)
      python: 3.9
    - if: branch IN (master, develop)
      python: 3.8
    - if: branch IN (master, develop)
      python: 3.6
    - if: branch IN (master, develop)
      python: pypy3


install: pip install -U tox coveralls

script:
  - tox -e $(echo py$TRAVIS_PYTHON_VERSION | tr -d . | sed -e 's/pypypy/pypy/')

cache: pip

# Coverall and Lint only in 3.7
after_success:
  - test $TRAVIS_PYTHON_VERSION = 3.7 && tox -e lint
  - test $TRAVIS_PYTHON_VERSION = 3.7 && coveralls

deploy:
  # Test PYPI
  - provider: pypi
    user: __token__
    password:
      secure: m/iNGZX8iIdta1ko/0yTZ994hM6aJqiLcgen1Au/DwgFYAbh2AWCFyQNeghqn4KwG1+LSb4TQdpGWgrx3lB2dFnHIVrkSYC25OBelg+1gmCO+7VUOM3Ysyxy2Av/fjR2N0xqxCwepr2xl5hUc4wdm+hKkKj13vhClQuQkp8quz2iagAuOsIHja1uDmoVM4IPQg+KBtQA1HpQp1f2v/O/qW4bfJKHqbhEzVXS5LMoN7LUh3iBjwwolPsuGE/3MwB9YgGZvdSIAsS/Wyam/7i7pSg8HgnXnRH3jucNZ84fh/1bVunpmyP8ebO+lhrryukkRRap82Vb7oQLN82SGqwFiBZZ+2LqCD4z/UOg67+6ZvTx0R06aK1WMpIwSd+sY5ohBHPIDR645m9m/z5N7JHY5ydeUi6NxRVTJjkfTRzjowV427r9UFgGFP/qXBRcgxB36FhXMw8q8tsNnKkB3wvmxPN7RbCUyQG7In2TxBuXCHiHXAGAM6B70ktHc3wK0dtRZF0hqSIQIqUlKiHjjL/IkwdYo5Fg/26HszczqlD0ZSD0uJq4BxJjQQ5di7vcgyu9BcP9rDHIenFZXW+ccMSVx0GD6bAUCJT/+RwWa3YARPojDoaDv+FcKeMBTIQFeOsi7lYwxqFL28YiGfSjQnkFsVmeH91YG0dW7u7l+GBZGsk=
    server: https://test.pypi.org/legacy/
    distributions: "sdist bdist_wheel"
    skip_existing: true
    on:
      branch: develop
      condition: $TRAVIS_PYTHON_VERSION == 3.7 || $TRAVIS_PYTHON_VERSION == 2.7
      repo: rado0x54/python-carson-living
  # Prod PYPI 3.7
  - provider: pypi
    user: __token__
    password:
      secure: Pu0F/Zd3vAkyLSAmtrQdgM8wEDy68UHH8hBoMWj8e3/jq0BjKBdcLRSFj9GnV7BM0zBCk0CmcX9/sXSWo1kkprvEmS+57zRcuXCLfk/oT1J9TRmbDPCEObBsrvNzQroXHwqX/OWqKJcaTv+NYE1bGzvoKUMGvd+1d9CdNbfD/pnxtrA7UkZUJargBvEYCKM/Yd/aYsluzobzZMcZ0tSUEvpRoXYBCCFv4/B+rfUECrxCiXnu7uhQg2MTAwgJBcu6qG0gd/1aKgCyD89Q20/vEFvHQv6dU2j6G2dQr41q+ek7OxUx52LHtbAz4a7QiNvceeFD2O1Q1wDBz04983StpAsxqAKg5PAD+dJdAIBc76r4gqckIYf5RSvpiwU+7pYXLDqt3d4lxtJpK9+6BRdEUqVzrPgGUi3Z6BK7QcTSxdT9r96gWUoI4VOZOHvjHTzSUI/Ymie894Inpn7I2ugfa+SpVam6sCon4QBwKJIu65OIpmH1uNYPU4IqWqhhf/5+8BqRZ6H7uK1d6fUClViRAynj14JjiaW5Cb1jlWrOnli1jnvTH6kZ8tcZhsagDxUDwD+BtaUQOaW/E9sv1bl9z7D1lKc5Lg9Udp09WMVFczaXWm56NBGUju6jQf+P7p6e1G7xVKEPOf9dI5rNf32RazoVEJsyW5jSEShKb32Eg5g="
    distributions: "sdist bdist_wheel"
    skip_existing: true
    on:
      tags: true
      condition: $TRAVIS_PYTHON_VERSION == 3.7 || $TRAVIS_PYTHON_VERSION == 2.7
      repo: rado0x54/python-carson-living
